import type { PlaceEntity } from "./types";
import { buildGoogleMapsUrl } from "./types";

export const beachesSeed: PlaceEntity[] = [
  {
    id: "beach-cala-varques",
    slug: "cala-varques",
    name: "Cala Varques",
    description: "Cala virgen con cuevas y arcos naturales, acceso por bosque sin servicios.",
    difficulty: "high",
    zone: "east",
    priceText: "Gratis",
    priceType: "free",
    town: "Manacor",
    googleMapsUrl: buildGoogleMapsUrl("Cala Varques Manacor Mallorca"),
    tags: ["wild", "caves", "hidden"],
  },
  {
    id: "beach-cala-tuent",
    slug: "cala-tuent",
    name: "Cala Tuent",
    description: "Cala aislada con grava, rodeada de montaña y muy poco turismo.",
    difficulty: "medium",
    zone: "north-west",
    priceText: "Gratis",
    priceType: "free",
    town: "Escorca",
    googleMapsUrl: buildGoogleMapsUrl("Cala Tuent Escorca Mallorca"),
    tags: ["remote", "mountains", "quiet"],
  },
  {
    id: "beach-cala-llombards",
    slug: "cala-llombards",
    name: "Cala Llombards",
    description: "Cala local poco turística con agua clara y entorno residencial.",
    difficulty: "low",
    zone: "south",
    priceText: "Gratis",
    priceType: "free",
    town: "Santanyí",
    googleMapsUrl: buildGoogleMapsUrl("Cala Llombards Santanyí Mallorca"),
    tags: ["clear-water", "local"],
  },
  {
    id: "beach-cala-salmunia",
    slug: "cala-salmunia",
    name: "Cala S'Almunia",
    description: "Cala rocosa con casitas de pescadores, muy estética pero sin arena.",
    difficulty: "medium",
    zone: "south",
    priceText: "Gratis",
    priceType: "free",
    town: "Santanyí",
    googleMapsUrl: buildGoogleMapsUrl("Cala S'Almunia Santanyí Mallorca"),
    tags: ["rocky", "photogenic"],
  },
  {
    id: "beach-calo-des-moro",
    slug: "calo-des-moro",
    name: "Caló des Moro",
    description: "Mini cala espectacular, acceso complicado y saturación en verano.",
    difficulty: "high",
    zone: "south",
    priceText: "Gratis",
    priceType: "free",
    town: "Santanyí",
    googleMapsUrl: buildGoogleMapsUrl("Caló des Moro Santanyí Mallorca"),
    tags: ["iconic", "small", "crowded"],
  },
  {
    id: "beach-cala-mitjana",
    slug: "cala-mitjana",
    name: "Cala Mitjana",
    description: "Cala pequeña escondida, poco accesible y muy tranquila.",
    difficulty: "high",
    zone: "east",
    priceText: "Gratis",
    priceType: "free",
    town: "Felanitx",
    googleMapsUrl: buildGoogleMapsUrl("Cala Mitjana Felanitx Mallorca"),
    tags: ["hidden", "quiet"],
  },
  {
    id: "beach-cala-magraner",
    slug: "cala-magraner",
    name: "Cala Magraner",
    description: "Cala salvaje con acantilados, popular para escalada.",
    difficulty: "high",
    zone: "east",
    priceText: "Gratis",
    priceType: "free",
    town: "Manacor",
    googleMapsUrl: buildGoogleMapsUrl("Cala Magraner Manacor Mallorca"),
    tags: ["cliffs", "climbing", "wild"],
  },
  {
    id: "beach-cala-pilota",
    slug: "cala-pilota",
    name: "Cala Pilota",
    description: "Cala virgen pequeña, ideal para snorkel y poco turismo.",
    difficulty: "medium",
    zone: "east",
    priceText: "Gratis",
    priceType: "free",
    town: "Manacor",
    googleMapsUrl: buildGoogleMapsUrl("Cala Pilota Manacor Mallorca"),
    tags: ["snorkel", "hidden"],
  },
  {
    id: "beach-cala-virgili",
    slug: "cala-virgili",
    name: "Cala Virgili",
    description: "Cala escondida con acceso por pista y caminata.",
    difficulty: "medium",
    zone: "east",
    priceText: "Gratis",
    priceType: "free",
    town: "Manacor",
    googleMapsUrl: buildGoogleMapsUrl("Cala Virgili Manacor Mallorca"),
    tags: ["track-access", "quiet"],
  },
  {
    id: "beach-es-carbo",
    slug: "es-carbo",
    name: "Es Carbó",
    description: "Playa virgen con caminata larga, pero recompensa alta.",
    difficulty: "high",
    zone: "south",
    priceText: "Gratis",
    priceType: "free",
    town: "Colònia Sant Jordi",
    googleMapsUrl: buildGoogleMapsUrl("Es Carbó Colònia Sant Jordi Mallorca"),
    tags: ["wild", "long-walk"],
  },
  {
    id: "beach-cala-en-basset",
    slug: "cala-en-basset",
    name: "Cala en Basset",
    description: "Cala totalmente salvaje, acceso hiking serio.",
    difficulty: "very-high",
    zone: "west",
    priceText: "Gratis",
    priceType: "free",
    town: "Sant Elm",
    googleMapsUrl: buildGoogleMapsUrl("Cala en Basset Sant Elm Mallorca"),
    tags: ["hike", "wild", "remote"],
  },
  {
    id: "beach-cala-deia",
    slug: "cala-deia",
    name: "Cala Deià",
    description: "Cala de piedra con restaurante, ambiente más exclusivo.",
    difficulty: "medium",
    zone: "west",
    priceText: "Gratis",
    priceType: "free",
    town: "Deià",
    googleMapsUrl: buildGoogleMapsUrl("Cala Deià Mallorca"),
    tags: ["stone-beach", "stylish"],
  },
  {
    id: "beach-cala-banyalbufar",
    slug: "cala-banyalbufar",
    name: "Cala Banyalbufar",
    description: "Pequeña cala entre terrazas agrícolas y acantilados.",
    difficulty: "medium",
    zone: "west",
    priceText: "Gratis",
    priceType: "free",
    town: "Banyalbufar",
    googleMapsUrl: buildGoogleMapsUrl("Cala Banyalbufar Mallorca"),
    tags: ["terraces", "cliffs"],
  },
  {
    id: "beach-cala-murta",
    slug: "cala-murta",
    name: "Cala Murta",
    description: "Cala escondida dentro de Formentor, acceso caminando.",
    difficulty: "medium",
    zone: "north",
    priceText: "Gratis",
    priceType: "free",
    town: "Formentor",
    googleMapsUrl: buildGoogleMapsUrl("Cala Murta Formentor Mallorca"),
    tags: ["formentor", "walk-access"],
  },
  {
    id: "beach-cala-figuera-formentor",
    slug: "cala-figuera-formentor",
    name: "Cala Figuera (Formentor)",
    description: "Cala aislada, difícil acceso y poca masificación.",
    difficulty: "high",
    zone: "north",
    priceText: "Gratis",
    priceType: "free",
    town: "Formentor",
    googleMapsUrl: buildGoogleMapsUrl("Cala Figuera Formentor Mallorca"),
    tags: ["remote", "formentor"],
  },
  {
    id: "beach-cala-estellencs",
    slug: "cala-estellencs",
    name: "Cala Estellencs",
    description: "Cala mixta roca y arena en pueblo tranquilo.",
    difficulty: "low",
    zone: "west",
    priceText: "Gratis",
    priceType: "free",
    town: "Estellencs",
    googleMapsUrl: buildGoogleMapsUrl("Cala Estellencs Mallorca"),
    tags: ["quiet", "village"],
  },
  {
    id: "beach-cala-sant-vicenc",
    slug: "cala-sant-vicenc",
    name: "Cala Sant Vicenç",
    description: "Conjunto de calas pequeñas con paisaje espectacular.",
    difficulty: "low",
    zone: "north",
    priceText: "Gratis",
    priceType: "free",
    town: "Pollença",
    googleMapsUrl: buildGoogleMapsUrl("Cala Sant Vicenç Pollença Mallorca"),
    tags: ["multiple-coves", "scenic"],
  },
  {
    id: "beach-cala-torta",
    slug: "cala-torta",
    name: "Cala Torta",
    description: "Cala salvaje con acceso por pista de tierra.",
    difficulty: "medium",
    zone: "north",
    priceText: "Gratis",
    priceType: "free",
    town: "Artà",
    googleMapsUrl: buildGoogleMapsUrl("Cala Torta Artà Mallorca"),
    tags: ["wild", "dirt-road"],
  },
  {
    id: "beach-cala-mesquida-lateral",
    slug: "cala-mesquida-lateral",
    name: "Cala Mesquida (zona escondida lateral)",
    description: "Parte menos concurrida lejos del acceso principal.",
    difficulty: "medium",
    zone: "north",
    priceText: "Gratis",
    priceType: "free",
    town: "Capdepera",
    googleMapsUrl: buildGoogleMapsUrl("Cala Mesquida Capdepera Mallorca"),
    tags: ["less-crowded", "side-area"],
  },
  {
    id: "beach-cala-mondrago-internal",
    slug: "cala-mondrago-internal",
    name: "Cala Mondragó (zonas internas)",
    description: "Parque natural con varias calas menos visibles.",
    difficulty: "low",
    zone: "south-east",
    priceText: "Gratis (parking ~6€)",
    priceType: "variable",
    town: "Santanyí",
    googleMapsUrl: buildGoogleMapsUrl("Cala Mondragó Santanyí Mallorca"),
    tags: ["natural-park", "multiple-coves"],
  },
];
