import type { PlaceEntity } from "./types";
import { buildGoogleMapsUrl } from "./types";

export const cafesSeed: PlaceEntity[] = [
  {
    id: "cafe-santal",
    slug: "santal",
    name: "Santal",
    description: "Café specialty minimalista.",
    difficulty: "low",
    zone: "west",
    priceText: "10–20€",
    priceType: "paid",
    town: "Palma",
    googleMapsUrl: buildGoogleMapsUrl("Santal Palma Mallorca"),
    tags: ["specialty-coffee", "minimal", "brunch"],
  },
  {
    id: "cafe-plant-shack",
    slug: "plant-shack",
    name: "Plant Shack",
    description: "Healthy brunch vegano.",
    difficulty: "low",
    zone: "west",
    priceText: "10–18€",
    priceType: "paid",
    town: "Palma",
    googleMapsUrl: buildGoogleMapsUrl("Plant Shack Palma Mallorca"),
    tags: ["vegan", "healthy", "brunch"],
  },
  {
    id: "cafe-mama-carmens",
    slug: "mama-carmens",
    name: "Mama Carmen's",
    description: "Café healthy muy popular.",
    difficulty: "low",
    zone: "west",
    priceText: "10–16€",
    priceType: "paid",
    town: "Palma",
    googleMapsUrl: buildGoogleMapsUrl("Mama Carmen's Palma Mallorca"),
    tags: ["healthy", "popular", "breakfast"],
  },
  {
    id: "cafe-nala-coffee",
    slug: "nala-coffee",
    name: "Nala Coffee",
    description: "Brunch aesthetic moderno.",
    difficulty: "low",
    zone: "west",
    priceText: "12–20€",
    priceType: "paid",
    town: "Palma",
    googleMapsUrl: buildGoogleMapsUrl("Nala Coffee Palma Mallorca"),
    tags: ["aesthetic", "modern", "brunch"],
  },
  {
    id: "cafe-fika-farina",
    slug: "fika-farina",
    name: "Fika Farina",
    description: "Bakery escandinavo.",
    difficulty: "low",
    zone: "west",
    priceText: "10–18€",
    priceType: "paid",
    town: "Palma",
    googleMapsUrl: buildGoogleMapsUrl("Fika Farina Palma Mallorca"),
    tags: ["bakery", "scandinavian", "coffee"],
  },
  {
    id: "cafe-elefante-cafe",
    slug: "elefante-cafe",
    name: "Elefante Café",
    description: "Brunch con vistas al mar.",
    difficulty: "low",
    zone: "west",
    priceText: "15–25€",
    priceType: "paid",
    town: "Cala Major",
    googleMapsUrl: buildGoogleMapsUrl("Elefante Café Cala Major Mallorca"),
    tags: ["sea-view", "brunch", "stylish"],
  },
  {
    id: "cafe-la-molienda",
    slug: "la-molienda",
    name: "La Molienda",
    description: "Café specialty de referencia.",
    difficulty: "low",
    zone: "west",
    priceText: "10–18€",
    priceType: "paid",
    town: "Palma",
    googleMapsUrl: buildGoogleMapsUrl("La Molienda Palma Mallorca"),
    tags: ["specialty-coffee", "reference", "palma"],
  },
  {
    id: "cafe-santina",
    slug: "santina",
    name: "Santina",
    description: "Brunch trendy.",
    difficulty: "low",
    zone: "west",
    priceText: "10–20€",
    priceType: "paid",
    town: "Palma",
    googleMapsUrl: buildGoogleMapsUrl("Santina Palma Mallorca"),
    tags: ["trendy", "brunch"],
  },
  {
    id: "cafe-cappuccino-cafe",
    slug: "cappuccino-cafe",
    name: "Cappuccino Café",
    description: "Clásico premium urbano.",
    difficulty: "low",
    zone: "west",
    priceText: "15–30€",
    priceType: "paid",
    town: "Palma",
    googleMapsUrl: buildGoogleMapsUrl("Cappuccino Café Palma Mallorca"),
    tags: ["classic", "premium", "urban"],
  },
  {
    id: "cafe-arabay-coffee",
    slug: "arabay-coffee",
    name: "Arabay Coffee",
    description: "Café de especialidad.",
    difficulty: "low",
    zone: "west",
    priceText: "5–15€",
    priceType: "paid",
    town: "Palma",
    googleMapsUrl: buildGoogleMapsUrl("Arabay Coffee Palma Mallorca"),
    tags: ["specialty-coffee", "coffee"],
  },
  {
    id: "cafe-cafe-riutort",
    slug: "cafe-riutort",
    name: "Café Riutort",
    description: "Brunch local.",
    difficulty: "low",
    zone: "west",
    priceText: "10–20€",
    priceType: "paid",
    town: "Palma",
    googleMapsUrl: buildGoogleMapsUrl("Café Riutort Palma Mallorca"),
    tags: ["local", "brunch"],
  },
  {
    id: "cafe-rosevelvet-bakery",
    slug: "rosevelvet-bakery",
    name: "Rosevelvet Bakery",
    description: "Café y repostería aesthetic.",
    difficulty: "low",
    zone: "west",
    priceText: "10–18€",
    priceType: "paid",
    town: "Palma",
    googleMapsUrl: buildGoogleMapsUrl("Rosevelvet Bakery Palma Mallorca"),
    tags: ["bakery", "aesthetic", "coffee"],
  },
  {
    id: "cafe-ziva-to-go",
    slug: "ziva-to-go",
    name: "Ziva To Go",
    description: "Healthy juices y opción ligera.",
    difficulty: "low",
    zone: "west",
    priceText: "8–15€",
    priceType: "paid",
    town: "Palma",
    googleMapsUrl: buildGoogleMapsUrl("Ziva To Go Palma Mallorca"),
    tags: ["healthy", "juices", "light-food"],
  },
  {
    id: "cafe-federal-cafe",
    slug: "federal-cafe",
    name: "Federal Café",
    description: "Brunch internacional.",
    difficulty: "low",
    zone: "west",
    priceText: "12–20€",
    priceType: "paid",
    town: "Palma",
    googleMapsUrl: buildGoogleMapsUrl("Federal Café Palma Mallorca"),
    tags: ["international", "brunch"],
  },
  {
    id: "cafe-dome-cafe",
    slug: "dome-cafe",
    name: "Dôme Café",
    description: "Brunch premium.",
    difficulty: "low",
    zone: "west",
    priceText: "15–25€",
    priceType: "paid",
    town: "Palma",
    googleMapsUrl: buildGoogleMapsUrl("Dôme Café Palma Mallorca"),
    tags: ["premium", "brunch"],
  },
  {
    id: "cafe-lemon-pie-tea-room",
    slug: "lemon-pie-tea-room",
    name: "Lemon Pie Tea Room",
    description: "Café tranquilo frente al mar.",
    difficulty: "medium",
    zone: "north",
    priceText: "10–18€",
    priceType: "paid",
    town: "Sóller",
    googleMapsUrl: buildGoogleMapsUrl("Lemon Pie Tea Room Sóller Mallorca"),
    tags: ["tea-room", "sea-view", "quiet"],
  },
  {
    id: "cafe-cafe-drac",
    slug: "cafe-drac",
    name: "Café Drac",
    description: "Café frente a cala.",
    difficulty: "medium",
    zone: "south",
    priceText: "10–20€",
    priceType: "paid",
    town: "Santanyí",
    googleMapsUrl: buildGoogleMapsUrl("Café Drac Santanyí Mallorca"),
    tags: ["cove-view", "coffee"],
  },
  {
    id: "cafe-santosha",
    slug: "santosha",
    name: "Santosha",
    description: "Healthy brunch moderno.",
    difficulty: "low",
    zone: "west",
    priceText: "10–18€",
    priceType: "paid",
    town: "Palma",
    googleMapsUrl: buildGoogleMapsUrl("Santosha Palma Mallorca"),
    tags: ["healthy", "modern", "brunch"],
  },
  {
    id: "cafe-es-pes-de-sa-palla",
    slug: "es-pes-de-sa-palla",
    name: "Es Pes de Sa Palla",
    description: "Café en pueblo con ambiente tranquilo.",
    difficulty: "low",
    zone: "north",
    priceText: "8–15€",
    priceType: "paid",
    town: "Sóller",
    googleMapsUrl: buildGoogleMapsUrl("Es Pes de Sa Palla Sóller Mallorca"),
    tags: ["village", "quiet", "coffee"],
  },
  {
    id: "cafe-cafe-paris",
    slug: "cafe-paris",
    name: "Café París",
    description: "Estilo clásico europeo.",
    difficulty: "low",
    zone: "west",
    priceText: "10–20€",
    priceType: "paid",
    town: "Palma",
    googleMapsUrl: buildGoogleMapsUrl("Café París Palma Mallorca"),
    tags: ["classic", "european", "urban"],
  },
];
