import type { MarketEntry } from "./types";
import { buildGoogleMapsUrl } from "./types";

export const marketsSeed: MarketEntry[] = [
  // === MONDAY ===
  {
    id: "market-monday-calvia",
    slug: "calvia-monday-market",
    name: "Calvià Market",
    day: "monday",
    town: "Calvià",
    area: "Calvià pueblo",
    zone: "west",
    priceText: "Gratis",
    priceType: "free",
    googleMapsUrl: buildGoogleMapsUrl("Calvià pueblo Mallorca"),
  },
  {
    id: "market-monday-caimari",
    slug: "caimari-monday-market",
    name: "Caimari Market",
    day: "monday",
    town: "Caimari",
    area: "Selva",
    zone: "north",
    priceText: "Gratis",
    priceType: "free",
    googleMapsUrl: buildGoogleMapsUrl("Caimari Selva Mallorca"),
  },
  {
    id: "market-monday-lloret-de-vistalegre",
    slug: "lloret-de-vistalegre-monday-market",
    name: "Lloret de Vistalegre Market",
    day: "monday",
    town: "Lloret de Vistalegre",
    zone: "center",
    priceText: "Gratis",
    priceType: "free",
    googleMapsUrl: buildGoogleMapsUrl("Lloret de Vistalegre Mallorca"),
  },
  {
    id: "market-monday-manacor",
    slug: "manacor-monday-market",
    name: "Manacor Market",
    day: "monday",
    town: "Manacor",
    zone: "east",
    priceText: "Gratis",
    priceType: "free",
    googleMapsUrl: buildGoogleMapsUrl("Manacor Mallorca"),
  },
  {
    id: "market-monday-montuiri",
    slug: "montuiri-monday-market",
    name: "Montuïri Market",
    day: "monday",
    town: "Montuïri",
    zone: "center",
    priceText: "Gratis",
    priceType: "free",
    googleMapsUrl: buildGoogleMapsUrl("Montuïri Mallorca"),
  },
  // === TUESDAY ===
  {
    id: "market-tuesday-alcudia",
    slug: "alcudia-tuesday-market",
    name: "Alcúdia Market",
    day: "tuesday",
    town: "Alcúdia",
    zone: "north",
    priceText: "Gratis",
    priceType: "free",
    googleMapsUrl: buildGoogleMapsUrl("Alcúdia Mallorca"),
  },
  {
    id: "market-tuesday-arta",
    slug: "arta-tuesday-market",
    name: "Artà Market",
    day: "tuesday",
    town: "Artà",
    zone: "east",
    priceText: "Gratis",
    priceType: "free",
    googleMapsUrl: buildGoogleMapsUrl("Artà Mallorca"),
  },
  {
    id: "market-tuesday-campanet",
    slug: "campanet-tuesday-market",
    name: "Campanet Market",
    day: "tuesday",
    town: "Campanet",
    zone: "north",
    priceText: "Gratis",
    priceType: "free",
    googleMapsUrl: buildGoogleMapsUrl("Campanet Mallorca"),
  },
  {
    id: "market-tuesday-colonia-sant-jordi",
    slug: "colonia-de-sant-jordi-tuesday-market",
    name: "Colònia de Sant Jordi Market",
    day: "tuesday",
    town: "Colònia de Sant Jordi",
    zone: "south",
    seasonalNotes: "May–October, evening/night",
    priceText: "Gratis",
    priceType: "free",
    googleMapsUrl: buildGoogleMapsUrl("Colònia de Sant Jordi Mallorca"),
  },
  {
    id: "market-tuesday-palma-ecologico",
    slug: "palma-ecological-tuesday-market",
    name: "Palma Mercado Ecológico",
    day: "tuesday",
    town: "Palma",
    area: "Mercado Ecológico",
    zone: "west",
    priceText: "Gratis",
    priceType: "free",
    googleMapsUrl: buildGoogleMapsUrl("Mercado Ecológico Palma Mallorca"),
  },
  {
    id: "market-tuesday-peguera",
    slug: "peguera-tuesday-market",
    name: "Peguera Market",
    day: "tuesday",
    town: "Peguera",
    zone: "west",
    priceText: "Gratis",
    priceType: "free",
    googleMapsUrl: buildGoogleMapsUrl("Peguera Mallorca"),
  },
  {
    id: "market-tuesday-porreres",
    slug: "porreres-tuesday-market",
    name: "Porreres Market",
    day: "tuesday",
    town: "Porreres",
    zone: "center",
    priceText: "Gratis",
    priceType: "free",
    googleMapsUrl: buildGoogleMapsUrl("Porreres Mallorca"),
  },
  {
    id: "market-tuesday-pina",
    slug: "pina-tuesday-market",
    name: "Pina Market",
    day: "tuesday",
    town: "Pina",
    area: "Algaida",
    zone: "center",
    priceText: "Gratis",
    priceType: "free",
    googleMapsUrl: buildGoogleMapsUrl("Pina Algaida Mallorca"),
  },
  {
    id: "market-tuesday-can-pastilla",
    slug: "can-pastilla-tuesday-market",
    name: "Can Pastilla Market",
    day: "tuesday",
    town: "Can Pastilla",
    area: "Palma",
    zone: "west",
    priceText: "Gratis",
    priceType: "free",
    googleMapsUrl: buildGoogleMapsUrl("Can Pastilla Palma Mallorca"),
  },
  {
    id: "market-tuesday-portocolom",
    slug: "portocolom-tuesday-market",
    name: "Portocolom Market",
    day: "tuesday",
    town: "Portocolom",
    zone: "east",
    priceText: "Gratis",
    priceType: "free",
    googleMapsUrl: buildGoogleMapsUrl("Portocolom Mallorca"),
  },
  {
    id: "market-tuesday-santa-margalida",
    slug: "santa-margalida-tuesday-market",
    name: "Santa Margalida Market",
    day: "tuesday",
    town: "Santa Margalida",
    zone: "north",
    priceText: "Gratis",
    priceType: "free",
    googleMapsUrl: buildGoogleMapsUrl("Santa Margalida Mallorca"),
  },
  // === WEDNESDAY ===
  {
    id: "market-wednesday-andratx",
    slug: "andratx-wednesday-market",
    name: "Andratx Market",
    day: "wednesday",
    town: "Andratx",
    zone: "west",
    priceText: "Gratis",
    priceType: "free",
    googleMapsUrl: buildGoogleMapsUrl("Andratx Mallorca"),
  },
  {
    id: "market-wednesday-bunyola",
    slug: "bunyola-wednesday-market",
    name: "Bunyola Market",
    day: "wednesday",
    town: "Bunyola",
    zone: "north",
    priceText: "Gratis",
    priceType: "free",
    googleMapsUrl: buildGoogleMapsUrl("Bunyola Mallorca"),
  },
  {
    id: "market-wednesday-capdepera",
    slug: "capdepera-wednesday-market",
    name: "Capdepera Market",
    day: "wednesday",
    town: "Capdepera",
    zone: "east",
    priceText: "Gratis",
    priceType: "free",
    googleMapsUrl: buildGoogleMapsUrl("Capdepera Mallorca"),
  },
  {
    id: "market-wednesday-deia",
    slug: "deia-wednesday-market",
    name: "Deià Market",
    day: "wednesday",
    town: "Deià",
    zone: "west",
    priceText: "Gratis",
    priceType: "free",
    googleMapsUrl: buildGoogleMapsUrl("Deià Mallorca"),
  },
  {
    id: "market-wednesday-el-toro",
    slug: "el-toro-wednesday-market",
    name: "El Toro Market",
    day: "wednesday",
    town: "El Toro",
    area: "Calvià",
    zone: "west",
    priceText: "Gratis",
    priceType: "free",
    googleMapsUrl: buildGoogleMapsUrl("El Toro Calvià Mallorca"),
  },
  {
    id: "market-wednesday-felanitx",
    slug: "felanitx-wednesday-market",
    name: "Felanitx Market",
    day: "wednesday",
    town: "Felanitx",
    zone: "east",
    priceText: "Gratis",
    priceType: "free",
    googleMapsUrl: buildGoogleMapsUrl("Felanitx Mallorca"),
  },
  {
    id: "market-wednesday-petra",
    slug: "petra-wednesday-market",
    name: "Petra Market",
    day: "wednesday",
    town: "Petra",
    zone: "center",
    priceText: "Gratis",
    priceType: "free",
    googleMapsUrl: buildGoogleMapsUrl("Petra Mallorca"),
  },
  {
    id: "market-wednesday-port-de-pollenca",
    slug: "port-de-pollenca-wednesday-market",
    name: "Port de Pollença Market",
    day: "wednesday",
    town: "Port de Pollença",
    zone: "north",
    priceText: "Gratis",
    priceType: "free",
    googleMapsUrl: buildGoogleMapsUrl("Port de Pollença Mallorca"),
  },
  {
    id: "market-wednesday-santanyi",
    slug: "santanyi-wednesday-market",
    name: "Santanyí Market",
    day: "wednesday",
    town: "Santanyí",
    zone: "south",
    priceText: "Gratis",
    priceType: "free",
    googleMapsUrl: buildGoogleMapsUrl("Santanyí Mallorca"),
  },
  {
    id: "market-wednesday-sencelles",
    slug: "sencelles-wednesday-market",
    name: "Sencelles Market",
    day: "wednesday",
    town: "Sencelles",
    zone: "center",
    priceText: "Gratis",
    priceType: "free",
    googleMapsUrl: buildGoogleMapsUrl("Sencelles Mallorca"),
  },
  {
    id: "market-wednesday-sineu",
    slug: "sineu-wednesday-market",
    name: "Sineu Market",
    day: "wednesday",
    town: "Sineu",
    zone: "center",
    priceText: "Gratis",
    priceType: "free",
    googleMapsUrl: buildGoogleMapsUrl("Sineu Mallorca"),
  },
  {
    id: "market-wednesday-vilafranca-de-bonany",
    slug: "vilafranca-de-bonany-wednesday-market",
    name: "Vilafranca de Bonany Market",
    day: "wednesday",
    town: "Vilafranca de Bonany",
    zone: "center",
    priceText: "Gratis",
    priceType: "free",
    googleMapsUrl: buildGoogleMapsUrl("Vilafranca de Bonany Mallorca"),
  },
  {
    id: "market-wednesday-cas-concos",
    slug: "cas-concos-wednesday-market",
    name: "Cas Concos Market",
    day: "wednesday",
    town: "Cas Concos",
    zone: "south",
    priceText: "Gratis",
    priceType: "free",
    googleMapsUrl: buildGoogleMapsUrl("Cas Concos Mallorca"),
  },
  {
    id: "market-wednesday-llucmajor",
    slug: "llucmajor-wednesday-market",
    name: "Llucmajor Market",
    day: "wednesday",
    town: "Llucmajor",
    zone: "south",
    priceText: "Gratis",
    priceType: "free",
    googleMapsUrl: buildGoogleMapsUrl("Llucmajor Mallorca"),
  },
  {
    id: "market-wednesday-maioris",
    slug: "maioris-wednesday-market",
    name: "Maioris Market",
    day: "wednesday",
    town: "Maioris",
    area: "Llucmajor",
    zone: "south",
    priceText: "Gratis",
    priceType: "free",
    googleMapsUrl: buildGoogleMapsUrl("Maioris Llucmajor Mallorca"),
  },
  {
    id: "market-wednesday-sa-pobla",
    slug: "sa-pobla-wednesday-market",
    name: "Sa Pobla Market",
    day: "wednesday",
    town: "Sa Pobla",
    zone: "north",
    priceText: "Gratis",
    priceType: "free",
    googleMapsUrl: buildGoogleMapsUrl("Sa Pobla Mallorca"),
  },
  {
    id: "market-wednesday-sa-rapita",
    slug: "sa-rapita-wednesday-market",
    name: "Sa Ràpita Market",
    day: "wednesday",
    town: "Sa Ràpita",
    zone: "south",
    priceText: "Gratis",
    priceType: "free",
    googleMapsUrl: buildGoogleMapsUrl("Sa Ràpita Mallorca"),
  },
  {
    id: "market-wednesday-coll-den-rabassa",
    slug: "es-coll-den-rabassa-wednesday-market",
    name: "Es Coll d'en Rabassa Market",
    day: "wednesday",
    town: "Es Coll d'en Rabassa",
    area: "Palma",
    zone: "west",
    priceText: "Gratis",
    priceType: "free",
    googleMapsUrl: buildGoogleMapsUrl("Es Coll d'en Rabassa Palma Mallorca"),
  },
  // === THURSDAY ===
  {
    id: "market-thursday-ariany",
    slug: "ariany-thursday-market",
    name: "Ariany Market",
    day: "thursday",
    town: "Ariany",
    zone: "center",
    priceText: "Gratis",
    priceType: "free",
    googleMapsUrl: buildGoogleMapsUrl("Ariany Mallorca"),
  },
  {
    id: "market-thursday-campos",
    slug: "campos-thursday-market",
    name: "Campos Market",
    day: "thursday",
    town: "Campos",
    zone: "south",
    priceText: "Gratis",
    priceType: "free",
    googleMapsUrl: buildGoogleMapsUrl("Campos Mallorca"),
  },
  {
    id: "market-thursday-consell",
    slug: "consell-thursday-market",
    name: "Consell Market",
    day: "thursday",
    town: "Consell",
    zone: "center",
    priceText: "Gratis",
    priceType: "free",
    googleMapsUrl: buildGoogleMapsUrl("Consell Mallorca"),
  },
  {
    id: "market-thursday-inca",
    slug: "inca-thursday-market",
    name: "Inca Market",
    day: "thursday",
    town: "Inca",
    zone: "center",
    priceText: "Gratis",
    priceType: "free",
    googleMapsUrl: buildGoogleMapsUrl("Inca Mallorca"),
  },
  {
    id: "market-thursday-magaluf",
    slug: "magaluf-thursday-market",
    name: "Magaluf Market",
    day: "thursday",
    town: "Magaluf",
    area: "Calvià",
    zone: "west",
    priceText: "Gratis",
    priceType: "free",
    googleMapsUrl: buildGoogleMapsUrl("Magaluf Calvià Mallorca"),
  },
  {
    id: "market-thursday-palmanyola",
    slug: "palmanyola-thursday-market",
    name: "Palmanyola Market",
    day: "thursday",
    town: "Palmanyola",
    zone: "center",
    priceText: "Gratis",
    priceType: "free",
    googleMapsUrl: buildGoogleMapsUrl("Palmanyola Mallorca"),
  },
  {
    id: "market-thursday-son-servera",
    slug: "son-servera-thursday-market",
    name: "Son Servera Market",
    day: "thursday",
    town: "Son Servera",
    zone: "east",
    priceText: "Gratis",
    priceType: "free",
    googleMapsUrl: buildGoogleMapsUrl("Son Servera Mallorca"),
  },
  {
    id: "market-thursday-ses-salines",
    slug: "ses-salines-thursday-market",
    name: "Ses Salines Market",
    day: "thursday",
    town: "Ses Salines",
    zone: "south",
    priceText: "Gratis",
    priceType: "free",
    googleMapsUrl: buildGoogleMapsUrl("Ses Salines Mallorca"),
  },
  {
    id: "market-thursday-sant-joan",
    slug: "sant-joan-thursday-market",
    name: "Sant Joan Market",
    day: "thursday",
    town: "Sant Joan",
    zone: "center",
    priceText: "Gratis",
    priceType: "free",
    googleMapsUrl: buildGoogleMapsUrl("Sant Joan Mallorca"),
  },
  {
    id: "market-thursday-el-arenal",
    slug: "el-arenal-thursday-market",
    name: "El Arenal Market",
    day: "thursday",
    town: "El Arenal",
    zone: "south",
    priceText: "Gratis",
    priceType: "free",
    googleMapsUrl: buildGoogleMapsUrl("El Arenal Mallorca"),
  },
  {
    id: "market-thursday-can-pastilla",
    slug: "can-pastilla-thursday-market",
    name: "Can Pastilla Market",
    day: "thursday",
    town: "Can Pastilla",
    area: "Palma",
    zone: "west",
    priceText: "Gratis",
    priceType: "free",
    googleMapsUrl: buildGoogleMapsUrl("Can Pastilla Palma Mallorca"),
  },
  // === FRIDAY ===
  {
    id: "market-friday-algaida",
    slug: "algaida-friday-market",
    name: "Algaida Market",
    day: "friday",
    town: "Algaida",
    zone: "center",
    priceText: "Gratis",
    priceType: "free",
    googleMapsUrl: buildGoogleMapsUrl("Algaida Mallorca"),
  },
  {
    id: "market-friday-binissalem",
    slug: "binissalem-friday-market",
    name: "Binissalem Market",
    day: "friday",
    town: "Binissalem",
    zone: "center",
    priceText: "Gratis",
    priceType: "free",
    googleMapsUrl: buildGoogleMapsUrl("Binissalem Mallorca"),
  },
  {
    id: "market-friday-can-picafort",
    slug: "can-picafort-friday-market",
    name: "Can Picafort Market",
    day: "friday",
    town: "Can Picafort",
    zone: "north",
    priceText: "Gratis",
    priceType: "free",
    googleMapsUrl: buildGoogleMapsUrl("Can Picafort Mallorca"),
  },
  {
    id: "market-friday-llucmajor",
    slug: "llucmajor-friday-market",
    name: "Llucmajor Market",
    day: "friday",
    town: "Llucmajor",
    zone: "south",
    priceText: "Gratis",
    priceType: "free",
    googleMapsUrl: buildGoogleMapsUrl("Llucmajor Mallorca"),
  },
  {
    id: "market-friday-maria-de-la-salut",
    slug: "maria-de-la-salut-friday-market",
    name: "Maria de la Salut Market",
    day: "friday",
    town: "Maria de la Salut",
    zone: "center",
    priceText: "Gratis",
    priceType: "free",
    googleMapsUrl: buildGoogleMapsUrl("Maria de la Salut Mallorca"),
  },
  {
    id: "market-friday-pont-dinca",
    slug: "pont-dinca-friday-market",
    name: "Pont d'Inca Market",
    day: "friday",
    town: "Pont d'Inca",
    area: "Marratxí",
    zone: "center",
    priceText: "Gratis",
    priceType: "free",
    googleMapsUrl: buildGoogleMapsUrl("Pont d'Inca Marratxí Mallorca"),
  },
  {
    id: "market-friday-son-ferrer",
    slug: "son-ferrer-friday-market",
    name: "Son Ferrer Market",
    day: "friday",
    town: "Son Ferrer",
    area: "Calvià",
    zone: "west",
    priceText: "Gratis",
    priceType: "free",
    googleMapsUrl: buildGoogleMapsUrl("Son Ferrer Calvià Mallorca"),
  },
  {
    id: "market-friday-son-servera",
    slug: "son-servera-friday-market",
    name: "Son Servera Market",
    day: "friday",
    town: "Son Servera",
    zone: "east",
    priceText: "Gratis",
    priceType: "free",
    googleMapsUrl: buildGoogleMapsUrl("Son Servera Mallorca"),
  },
  {
    id: "market-friday-son-carrio",
    slug: "son-carrio-friday-market",
    name: "Son Carrió Market",
    day: "friday",
    town: "Son Carrió",
    zone: "east",
    priceText: "Gratis",
    priceType: "free",
    googleMapsUrl: buildGoogleMapsUrl("Son Carrió Mallorca"),
  },
  {
    id: "market-friday-sa-cabaneta",
    slug: "sa-cabaneta-friday-market",
    name: "Sa Cabaneta Market",
    day: "friday",
    town: "Sa Cabaneta",
    zone: "center",
    priceText: "Gratis",
    priceType: "free",
    googleMapsUrl: buildGoogleMapsUrl("Sa Cabaneta Mallorca"),
  },
  // === SATURDAY ===
  {
    id: "market-saturday-alaro",
    slug: "alaro-saturday-market",
    name: "Alaró Market",
    day: "saturday",
    town: "Alaró",
    zone: "west",
    priceText: "Gratis",
    priceType: "free",
    googleMapsUrl: buildGoogleMapsUrl("Alaró Mallorca"),
  },
  {
    id: "market-saturday-ariany",
    slug: "ariany-saturday-market",
    name: "Ariany Market",
    day: "saturday",
    town: "Ariany",
    zone: "center",
    priceText: "Gratis",
    priceType: "free",
    googleMapsUrl: buildGoogleMapsUrl("Ariany Mallorca"),
  },
  {
    id: "market-saturday-arta",
    slug: "arta-saturday-market",
    name: "Artà Market",
    day: "saturday",
    town: "Artà",
    zone: "east",
    priceText: "Gratis",
    priceType: "free",
    googleMapsUrl: buildGoogleMapsUrl("Artà Mallorca"),
  },
  {
    id: "market-saturday-biniali",
    slug: "biniali-saturday-market",
    name: "Biniali Market",
    day: "saturday",
    town: "Biniali",
    area: "Sencelles",
    zone: "center",
    priceText: "Gratis",
    priceType: "free",
    googleMapsUrl: buildGoogleMapsUrl("Biniali Sencelles Mallorca"),
  },
  {
    id: "market-saturday-buger",
    slug: "buger-saturday-market",
    name: "Búger Market",
    day: "saturday",
    town: "Búger",
    zone: "north",
    priceText: "Gratis",
    priceType: "free",
    googleMapsUrl: buildGoogleMapsUrl("Búger Mallorca"),
  },
  {
    id: "market-saturday-bunyola",
    slug: "bunyola-saturday-market",
    name: "Bunyola Market",
    day: "saturday",
    town: "Bunyola",
    zone: "north",
    priceText: "Gratis",
    priceType: "free",
    googleMapsUrl: buildGoogleMapsUrl("Bunyola Mallorca"),
  },
  {
    id: "market-saturday-cala-ratjada",
    slug: "cala-ratjada-saturday-market",
    name: "Cala Ratjada Market",
    day: "saturday",
    town: "Cala Ratjada",
    zone: "east",
    priceText: "Gratis",
    priceType: "free",
    googleMapsUrl: buildGoogleMapsUrl("Cala Ratjada Mallorca"),
  },
  {
    id: "market-saturday-campos",
    slug: "campos-saturday-market",
    name: "Campos Market",
    day: "saturday",
    town: "Campos",
    zone: "south",
    priceText: "Gratis",
    priceType: "free",
    googleMapsUrl: buildGoogleMapsUrl("Campos Mallorca"),
  },
  {
    id: "market-saturday-costitx",
    slug: "costitx-saturday-market",
    name: "Costitx Market",
    day: "saturday",
    town: "Costitx",
    zone: "center",
    priceText: "Gratis",
    priceType: "free",
    googleMapsUrl: buildGoogleMapsUrl("Costitx Mallorca"),
  },
  {
    id: "market-saturday-esporles",
    slug: "esporles-saturday-market",
    name: "Esporles Market",
    day: "saturday",
    town: "Esporles",
    zone: "west",
    priceText: "Gratis",
    priceType: "free",
    googleMapsUrl: buildGoogleMapsUrl("Esporles Mallorca"),
  },
  {
    id: "market-saturday-lloseta",
    slug: "lloseta-saturday-market",
    name: "Lloseta Market",
    day: "saturday",
    town: "Lloseta",
    zone: "center",
    priceText: "Gratis",
    priceType: "free",
    googleMapsUrl: buildGoogleMapsUrl("Lloseta Mallorca"),
  },
  {
    id: "market-saturday-palma-ecologico",
    slug: "palma-ecological-saturday-market",
    name: "Palma Mercado Ecológico",
    day: "saturday",
    town: "Palma",
    area: "Mercado Ecológico",
    zone: "west",
    priceText: "Gratis",
    priceType: "free",
    googleMapsUrl: buildGoogleMapsUrl("Mercado Ecológico Palma Mallorca"),
  },
  {
    id: "market-saturday-santa-eugenia",
    slug: "santa-eugenia-saturday-market",
    name: "Santa Eugènia Market",
    day: "saturday",
    town: "Santa Eugènia",
    zone: "center",
    priceText: "Gratis",
    priceType: "free",
    googleMapsUrl: buildGoogleMapsUrl("Santa Eugènia Mallorca"),
  },
  {
    id: "market-saturday-santa-margalida",
    slug: "santa-margalida-saturday-market",
    name: "Santa Margalida Market",
    day: "saturday",
    town: "Santa Margalida",
    zone: "north",
    priceText: "Gratis",
    priceType: "free",
    googleMapsUrl: buildGoogleMapsUrl("Santa Margalida Mallorca"),
  },
  {
    id: "market-saturday-santanyi",
    slug: "santanyi-saturday-market",
    name: "Santanyí Market",
    day: "saturday",
    town: "Santanyí",
    zone: "south",
    priceText: "Gratis",
    priceType: "free",
    googleMapsUrl: buildGoogleMapsUrl("Santanyí Mallorca"),
  },
  {
    id: "market-saturday-soller",
    slug: "soller-saturday-market",
    name: "Sóller Market",
    day: "saturday",
    town: "Sóller",
    zone: "north",
    priceText: "Gratis",
    priceType: "free",
    googleMapsUrl: buildGoogleMapsUrl("Sóller Mallorca"),
  },
  {
    id: "market-saturday-santa-ponca",
    slug: "santa-ponca-saturday-market",
    name: "Santa Ponça Market",
    day: "saturday",
    town: "Santa Ponça",
    zone: "west",
    priceText: "Gratis",
    priceType: "free",
    googleMapsUrl: buildGoogleMapsUrl("Santa Ponça Mallorca"),
  },
  {
    id: "market-saturday-palmanyola",
    slug: "palmanyola-saturday-market",
    name: "Palmanyola Market",
    day: "saturday",
    town: "Palmanyola",
    zone: "center",
    priceText: "Gratis",
    priceType: "free",
    googleMapsUrl: buildGoogleMapsUrl("Palmanyola Mallorca"),
  },
  {
    id: "market-saturday-puigpunyent",
    slug: "puigpunyent-saturday-market",
    name: "Puigpunyent Market",
    day: "saturday",
    town: "Puigpunyent",
    zone: "west",
    priceText: "Gratis",
    priceType: "free",
    googleMapsUrl: buildGoogleMapsUrl("Puigpunyent Mallorca"),
  },
  {
    id: "market-saturday-sa-rapita",
    slug: "sa-rapita-saturday-market",
    name: "Sa Ràpita Market",
    day: "saturday",
    town: "Sa Ràpita",
    zone: "south",
    priceText: "Gratis",
    priceType: "free",
    googleMapsUrl: buildGoogleMapsUrl("Sa Ràpita Mallorca"),
  },
  {
    id: "market-saturday-sencelles",
    slug: "sencelles-saturday-market",
    name: "Sencelles Market",
    day: "saturday",
    town: "Sencelles",
    zone: "center",
    notes: "1st Saturday of the month",
    priceText: "Gratis",
    priceType: "free",
    googleMapsUrl: buildGoogleMapsUrl("Sencelles Mallorca"),
  },
  {
    id: "market-saturday-coll-den-rabassa",
    slug: "es-coll-den-rabassa-saturday-market",
    name: "Es Coll d'en Rabassa Market",
    day: "saturday",
    town: "Es Coll d'en Rabassa",
    area: "Palma",
    zone: "west",
    priceText: "Gratis",
    priceType: "free",
    googleMapsUrl: buildGoogleMapsUrl("Es Coll d'en Rabassa Palma Mallorca"),
  },
  {
    id: "market-saturday-son-ferriol",
    slug: "son-ferriol-saturday-market",
    name: "Son Ferriol Market",
    day: "saturday",
    town: "Son Ferriol",
    area: "Palma",
    zone: "west",
    priceText: "Gratis",
    priceType: "free",
    googleMapsUrl: buildGoogleMapsUrl("Son Ferriol Palma Mallorca"),
  },
  {
    id: "market-saturday-son-fusteret",
    slug: "son-fusteret-saturday-market",
    name: "Son Fusteret Market",
    day: "saturday",
    town: "Son Fusteret",
    area: "Palma",
    zone: "west",
    notes: "flea market",
    priceText: "Gratis",
    priceType: "free",
    googleMapsUrl: buildGoogleMapsUrl("Son Fusteret Palma Mallorca"),
  },
  {
    id: "market-saturday-portocolom",
    slug: "portocolom-saturday-market",
    name: "Portocolom Market",
    day: "saturday",
    town: "Portocolom",
    zone: "east",
    priceText: "Gratis",
    priceType: "free",
    googleMapsUrl: buildGoogleMapsUrl("Portocolom Mallorca"),
  },
  {
    id: "market-saturday-shorta",
    slug: "shorta-saturday-market",
    name: "s'Horta Market",
    day: "saturday",
    town: "s'Horta",
    zone: "east",
    priceText: "Gratis",
    priceType: "free",
    googleMapsUrl: buildGoogleMapsUrl("s'Horta Mallorca"),
  },
  // === SUNDAY ===
  {
    id: "market-sunday-alcudia",
    slug: "alcudia-sunday-market",
    name: "Alcúdia Market",
    day: "sunday",
    town: "Alcúdia",
    zone: "north",
    priceText: "Gratis",
    priceType: "free",
    googleMapsUrl: buildGoogleMapsUrl("Alcúdia Mallorca"),
  },
  {
    id: "market-sunday-consell",
    slug: "consell-sunday-market",
    name: "Consell Market",
    day: "sunday",
    town: "Consell",
    zone: "center",
    priceText: "Gratis",
    priceType: "free",
    googleMapsUrl: buildGoogleMapsUrl("Consell Mallorca"),
  },
  {
    id: "market-sunday-felanitx",
    slug: "felanitx-sunday-market",
    name: "Felanitx Market",
    day: "sunday",
    town: "Felanitx",
    zone: "east",
    priceText: "Gratis",
    priceType: "free",
    googleMapsUrl: buildGoogleMapsUrl("Felanitx Mallorca"),
  },
  {
    id: "market-sunday-llucmajor",
    slug: "llucmajor-sunday-market",
    name: "Llucmajor Market",
    day: "sunday",
    town: "Llucmajor",
    zone: "south",
    priceText: "Gratis",
    priceType: "free",
    googleMapsUrl: buildGoogleMapsUrl("Llucmajor Mallorca"),
  },
  {
    id: "market-sunday-muro",
    slug: "muro-sunday-market",
    name: "Muro Market",
    day: "sunday",
    town: "Muro",
    zone: "north",
    priceText: "Gratis",
    priceType: "free",
    googleMapsUrl: buildGoogleMapsUrl("Muro Mallorca"),
  },
  {
    id: "market-sunday-palmanova",
    slug: "palmanova-sunday-market",
    name: "Palmanova Market",
    day: "sunday",
    town: "Palmanova",
    area: "Son Caliu",
    zone: "west",
    priceText: "Gratis",
    priceType: "free",
    googleMapsUrl: buildGoogleMapsUrl("Palmanova Son Caliu Mallorca"),
  },
  {
    id: "market-sunday-pollenca",
    slug: "pollenca-sunday-market",
    name: "Pollença Market",
    day: "sunday",
    town: "Pollença",
    zone: "north",
    priceText: "Gratis",
    priceType: "free",
    googleMapsUrl: buildGoogleMapsUrl("Pollença Mallorca"),
  },
  {
    id: "market-sunday-porto-cristo",
    slug: "porto-cristo-sunday-market",
    name: "Porto Cristo Market",
    day: "sunday",
    town: "Porto Cristo",
    zone: "east",
    priceText: "Gratis",
    priceType: "free",
    googleMapsUrl: buildGoogleMapsUrl("Porto Cristo Mallorca"),
  },
  {
    id: "market-sunday-sa-pobla",
    slug: "sa-pobla-sunday-market",
    name: "Sa Pobla Market",
    day: "sunday",
    town: "Sa Pobla",
    zone: "north",
    priceText: "Gratis",
    priceType: "free",
    googleMapsUrl: buildGoogleMapsUrl("Sa Pobla Mallorca"),
  },
  {
    id: "market-sunday-santa-maria-del-cami",
    slug: "santa-maria-del-cami-sunday-market",
    name: "Santa Maria del Camí Market",
    day: "sunday",
    town: "Santa Maria del Camí",
    zone: "center",
    priceText: "Gratis",
    priceType: "free",
    googleMapsUrl: buildGoogleMapsUrl("Santa Maria del Camí Mallorca"),
  },
  {
    id: "market-sunday-valldemossa",
    slug: "valldemossa-sunday-market",
    name: "Valldemossa Market",
    day: "sunday",
    town: "Valldemossa",
    zone: "west",
    priceText: "Gratis",
    priceType: "free",
    googleMapsUrl: buildGoogleMapsUrl("Valldemossa Mallorca"),
  },
  {
    id: "market-sunday-inca",
    slug: "inca-sunday-market",
    name: "Inca Market",
    day: "sunday",
    town: "Inca",
    zone: "center",
    priceText: "Gratis",
    priceType: "free",
    googleMapsUrl: buildGoogleMapsUrl("Inca Mallorca"),
  },
];
