import type { PlaceEntity } from "./types";
import { buildGoogleMapsUrl } from "./types";

export const pointsOfInterestSeed: PlaceEntity[] = [
  {
    id: "poi-castell-de-bellver",
    slug: "castell-de-bellver",
    name: "Castell de Bellver",
    description: "Castillo circular único con vistas sobre Palma.",
    difficulty: "low",
    zone: "west",
    priceText: "4€",
    priceType: "paid",
    town: "Palma",
    googleMapsUrl: buildGoogleMapsUrl("Castell de Bellver Palma Mallorca"),
    tags: ["castle", "viewpoint", "history"],
  },
  {
    id: "poi-barranc-de-biniaraix",
    slug: "barranc-de-biniaraix",
    name: "Barranc de Biniaraix",
    description: "Ruta brutal de montaña en entorno de piedra y bancales.",
    difficulty: "high",
    zone: "north",
    priceText: "Gratis",
    priceType: "free",
    town: "Sóller",
    googleMapsUrl: buildGoogleMapsUrl("Barranc de Biniaraix Sóller Mallorca"),
    tags: ["hiking", "mountains", "stone-path"],
  },
  {
    id: "poi-can-lis",
    slug: "can-lis",
    name: "Can Lis",
    description: "Casa icónica frente al mar de gran interés arquitectónico.",
    difficulty: "medium",
    zone: "east",
    priceText: "Limitado",
    priceType: "variable",
    town: "Portopetro",
    googleMapsUrl: buildGoogleMapsUrl("Can Lis Portopetro Mallorca"),
    tags: ["architecture", "iconic", "sea-view"],
  },
  {
    id: "poi-stick-no-bills",
    slug: "stick-no-bills",
    name: "Stick No Bills",
    description: "Espacio artístico vintage con fuerte identidad visual.",
    difficulty: "low",
    zone: "west",
    priceText: "Gratis",
    priceType: "free",
    town: "Palma",
    googleMapsUrl: buildGoogleMapsUrl("Stick No Bills Palma Mallorca"),
    tags: ["art", "design", "vintage"],
  },
  {
    id: "poi-viti-vinci",
    slug: "viti-vinci",
    name: "Viti Vinci",
    description: "Perfumería artesanal con propuesta sensorial singular.",
    difficulty: "low",
    zone: "west",
    priceText: "Gratis",
    priceType: "free",
    town: "Palma",
    googleMapsUrl: buildGoogleMapsUrl("Viti Vinci Palma Mallorca"),
    tags: ["perfume", "artisan", "boutique"],
  },
  {
    id: "poi-es-calderers",
    slug: "es-calderers",
    name: "Es Calderers",
    description: "Finca histórica rural con valor patrimonial.",
    difficulty: "low",
    zone: "center",
    priceText: "Pago",
    priceType: "paid",
    town: "Sant Joan",
    googleMapsUrl: buildGoogleMapsUrl("Es Calderers Sant Joan Mallorca"),
    tags: ["heritage", "estate", "history"],
  },
  {
    id: "poi-torre-de-canyamel",
    slug: "torre-de-canyamel",
    name: "Torre de Canyamel",
    description: "Torre medieval bien conservada.",
    difficulty: "low",
    zone: "east",
    priceText: "5–10€",
    priceType: "paid",
    town: "Capdepera",
    googleMapsUrl: buildGoogleMapsUrl("Torre de Canyamel Mallorca"),
    tags: ["tower", "medieval", "history"],
  },
  {
    id: "poi-cuevas-de-arta",
    slug: "cuevas-de-arta",
    name: "Cuevas de Artà",
    description: "Cuevas espectaculares menos masificadas que otras opciones de la isla.",
    difficulty: "low",
    zone: "east",
    priceText: "15€",
    priceType: "paid",
    town: "Artà",
    googleMapsUrl: buildGoogleMapsUrl("Cuevas de Artà Mallorca"),
    tags: ["caves", "nature", "geology"],
  },
  {
    id: "poi-santuario-de-lluc",
    slug: "santuario-de-lluc",
    name: "Santuario de Lluc",
    description: "Centro espiritual en plena montaña.",
    difficulty: "low",
    zone: "north",
    priceText: "Gratis",
    priceType: "free",
    town: "Escorca",
    googleMapsUrl: buildGoogleMapsUrl("Santuario de Lluc Mallorca"),
    tags: ["sanctuary", "mountains", "spiritual"],
  },
  {
    id: "poi-real-cartuja",
    slug: "real-cartuja",
    name: "La Real Cartuja",
    description: "Monasterio histórico y uno de los enclaves culturales más conocidos.",
    difficulty: "low",
    zone: "west",
    priceText: "12€",
    priceType: "paid",
    town: "Valldemossa",
    googleMapsUrl: buildGoogleMapsUrl("Real Cartuja Valldemossa Mallorca"),
    tags: ["monastery", "culture", "heritage"],
  },
  {
    id: "poi-jardines-de-alfabia",
    slug: "jardines-de-alfabia",
    name: "Jardines de Alfàbia",
    description: "Jardines históricos con influencia árabe.",
    difficulty: "low",
    zone: "north",
    priceText: "8€",
    priceType: "paid",
    town: "Bunyola",
    googleMapsUrl: buildGoogleMapsUrl("Jardines de Alfàbia Bunyola Mallorca"),
    tags: ["gardens", "historic", "arabic-influence"],
  },
  {
    id: "poi-museo-sa-bassa-blanca",
    slug: "museo-sa-bassa-blanca",
    name: "Museo Sa Bassa Blanca",
    description: "Arte y naturaleza en un enclave singular.",
    difficulty: "medium",
    zone: "north",
    priceText: "15€",
    priceType: "paid",
    town: "Alcúdia",
    googleMapsUrl: buildGoogleMapsUrl("Museo Sa Bassa Blanca Alcúdia Mallorca"),
    tags: ["museum", "art", "nature"],
  },
  {
    id: "poi-son-marroig",
    slug: "son-marroig",
    name: "Son Marroig",
    description: "Casa histórica con uno de los miradores más conocidos de la Tramuntana.",
    difficulty: "low",
    zone: "west",
    priceText: "4€",
    priceType: "paid",
    town: "Deià",
    googleMapsUrl: buildGoogleMapsUrl("Son Marroig Deià Mallorca"),
    tags: ["viewpoint", "historic-house", "tramuntana"],
  },
  {
    id: "poi-torre-des-verger",
    slug: "torre-des-verger",
    name: "Torre des Verger",
    description: "Torre costera histórica con gran valor visual.",
    difficulty: "low",
    zone: "west",
    priceText: "Gratis",
    priceType: "free",
    town: "Banyalbufar",
    googleMapsUrl: buildGoogleMapsUrl("Torre des Verger Banyalbufar Mallorca"),
    tags: ["tower", "coast", "viewpoint"],
  },
  {
    id: "poi-faro-de-formentor",
    slug: "faro-de-formentor",
    name: "Faro de Formentor",
    description: "Faro icónico en uno de los paisajes más potentes del norte.",
    difficulty: "medium",
    zone: "north",
    priceText: "Gratis",
    priceType: "free",
    town: "Formentor",
    googleMapsUrl: buildGoogleMapsUrl("Faro de Formentor Mallorca"),
    tags: ["lighthouse", "scenic", "north"],
  },
  {
    id: "poi-ermita-de-bonany",
    slug: "ermita-de-bonany",
    name: "Ermita de Bonany",
    description: "Mirador y enclave religioso sobre colina.",
    difficulty: "medium",
    zone: "center",
    priceText: "Gratis",
    priceType: "free",
    town: "Petra",
    googleMapsUrl: buildGoogleMapsUrl("Ermita de Bonany Petra Mallorca"),
    tags: ["ermita", "viewpoint", "hill"],
  },
  {
    id: "poi-puig-de-sant-salvador",
    slug: "puig-de-sant-salvador",
    name: "Puig de Sant Salvador",
    description: "Mirador de montaña con fuerte sensación panorámica.",
    difficulty: "medium",
    zone: "east",
    priceText: "Gratis",
    priceType: "free",
    town: "Felanitx",
    googleMapsUrl: buildGoogleMapsUrl("Puig de Sant Salvador Felanitx Mallorca"),
    tags: ["mountain", "viewpoint", "panoramic"],
  },
  {
    id: "poi-iglesia-de-sant-joan",
    slug: "iglesia-de-sant-joan",
    name: "Iglesia de Sant Joan",
    description: "Punto de interés en un pueblo auténtico del centro de la isla.",
    difficulty: "low",
    zone: "center",
    priceText: "Gratis",
    priceType: "free",
    town: "Sant Joan",
    googleMapsUrl: buildGoogleMapsUrl("Iglesia de Sant Joan Mallorca"),
    tags: ["church", "village", "local"],
  },
  {
    id: "poi-calle-olmos",
    slug: "calle-olmos",
    name: "Calle Olmos",
    description: "Calle comercial histórica en Palma.",
    difficulty: "low",
    zone: "west",
    priceText: "Gratis",
    priceType: "free",
    town: "Palma",
    googleMapsUrl: buildGoogleMapsUrl("Calle Olmos Palma Mallorca"),
    tags: ["shopping", "urban", "historic"],
  },
  {
    id: "poi-plaza-gomila",
    slug: "plaza-gomila",
    name: "Plaza Gomila",
    description: "Zona urbana en transformación cultural.",
    difficulty: "low",
    zone: "west",
    priceText: "Gratis",
    priceType: "free",
    town: "Palma",
    googleMapsUrl: buildGoogleMapsUrl("Plaza Gomila Palma Mallorca"),
    tags: ["urban", "culture", "city"],
  },
];
