import type { RestaurantEntity } from "./types";
import { buildGoogleMapsUrl } from "./types";

export const restaurantsSeed: RestaurantEntity[] = [
  {
    id: "restaurant-casa-maruka",
    slug: "casa-maruka",
    name: "Casa Maruka",
    description: "Cocina tradicional potente, muy local y poco turística.",
    difficulty: "low",
    zone: "west",
    priceText: "40–50€",
    priceType: "paid",
    town: "Palma",
    googleMapsUrl: buildGoogleMapsUrl("Casa Maruka Palma Mallorca"),
    tags: ["local", "traditional", "palma"],
  },
  {
    id: "restaurant-bens-davall",
    slug: "bens-davall",
    name: "Bens d'Avall",
    description: "Restaurante en acantilado con vistas brutales.",
    difficulty: "medium",
    zone: "north-west",
    priceText: "70–120€",
    priceType: "paid",
    town: "Sóller",
    googleMapsUrl: buildGoogleMapsUrl("Bens d'Avall Sóller Mallorca"),
    tags: ["views", "clifftop", "premium"],
  },
  {
    id: "restaurant-miceli",
    slug: "miceli",
    name: "Miceli",
    description: "Cocina mallorquina moderna en un pueblo tranquilo.",
    difficulty: "medium",
    zone: "north",
    priceText: "40–60€",
    priceType: "paid",
    town: "Selva",
    googleMapsUrl: buildGoogleMapsUrl("Miceli Selva Mallorca"),
    tags: ["slow-food", "mallorcan", "village"],
  },
  {
    id: "restaurant-ca-na-toneta",
    slug: "ca-na-toneta",
    name: "Ca Na Toneta",
    description: "Cocina estacional KM0 muy cuidada.",
    difficulty: "medium",
    zone: "north",
    priceText: "80–100€",
    priceType: "paid",
    town: "Caimari",
    googleMapsUrl: buildGoogleMapsUrl("Ca Na Toneta Caimari Mallorca"),
    tags: ["km0", "seasonal", "mallorcan"],
  },
  {
    id: "restaurant-santi-taura-dins",
    slug: "santi-taura-dins",
    name: "Santi Taura (DINS)",
    description: "Gastronomía local elevada.",
    difficulty: "low",
    zone: "west",
    priceText: "90–120€",
    priceType: "paid",
    town: "Palma",
    googleMapsUrl: buildGoogleMapsUrl("Santi Taura DINS Palma Mallorca"),
    tags: ["fine-dining", "palma", "tasting-menu"],
  },
  {
    id: "restaurant-vandal",
    slug: "vandal",
    name: "Vandal",
    description: "Cocina creativa internacional, ambiente urbano.",
    difficulty: "low",
    zone: "west",
    priceText: "30–50€",
    priceType: "paid",
    town: "Palma",
    googleMapsUrl: buildGoogleMapsUrl("Vandal Palma Mallorca"),
    tags: ["creative", "urban", "palma"],
  },
  {
    id: "restaurant-casa-miss",
    slug: "casa-miss",
    name: "Casa Miss",
    description: "Restaurante mediterráneo en zona menos turística.",
    difficulty: "low",
    zone: "west",
    priceText: "25–40€",
    priceType: "paid",
    town: "Palma",
    googleMapsUrl: buildGoogleMapsUrl("Casa Miss Palma Mallorca"),
    tags: ["mediterranean", "palma"],
  },
  {
    id: "restaurant-es-verger",
    slug: "es-verger",
    name: "Es Verger",
    description: "Restaurante de montaña famoso por el cordero.",
    difficulty: "high",
    zone: "west",
    priceText: "25–35€",
    priceType: "paid",
    town: "Alaró",
    googleMapsUrl: buildGoogleMapsUrl("Es Verger Alaró Mallorca"),
    tags: ["mountain", "lamb", "rustic"],
  },
  {
    id: "restaurant-can-punyetes",
    slug: "can-punyetes",
    name: "Can Punyetes",
    description: "Cocina catalana y mallorquina auténtica.",
    difficulty: "low",
    zone: "west",
    priceText: "20–30€",
    priceType: "paid",
    town: "Palma",
    googleMapsUrl: buildGoogleMapsUrl("Can Punyetes Palma Mallorca"),
    tags: ["traditional", "grill", "palma"],
  },
  {
    id: "restaurant-el-camino",
    slug: "el-camino",
    name: "El Camino",
    description: "Barra gastronómica tipo chef table.",
    difficulty: "low",
    zone: "west",
    priceText: "50–70€",
    priceType: "paid",
    town: "Palma",
    googleMapsUrl: buildGoogleMapsUrl("El Camino Palma Mallorca"),
    tags: ["chef-table", "bar", "palma"],
  },
  {
    id: "restaurant-sa-foradada",
    slug: "sa-foradada-restaurante",
    name: "Sa Foradada Restaurante",
    description: "Restaurante remoto junto al mar.",
    difficulty: "high",
    zone: "west",
    priceText: "40–60€",
    priceType: "paid",
    town: "Deià",
    googleMapsUrl: buildGoogleMapsUrl("Sa Foradada Restaurante Deià Mallorca"),
    tags: ["remote", "sea-view", "sunset"],
  },
  {
    id: "restaurant-can-gavella",
    slug: "can-gavella",
    name: "Can Gavella",
    description: "Restaurante local en zona rural.",
    difficulty: "medium",
    zone: "north",
    priceText: "20–35€",
    priceType: "paid",
    town: "Muro",
    googleMapsUrl: buildGoogleMapsUrl("Can Gavella Muro Mallorca"),
    tags: ["rural", "local"],
  },
  {
    id: "restaurant-nama",
    slug: "nama",
    name: "Restaurante Nama",
    description: "Fusión asiática en Port d'Andratx.",
    difficulty: "low",
    zone: "west",
    priceText: "40–70€",
    priceType: "paid",
    town: "Andratx",
    googleMapsUrl: buildGoogleMapsUrl("Nama Port d'Andratx Mallorca"),
    tags: ["asian-fusion", "port", "stylish"],
  },
  {
    id: "restaurant-sa-roqueta",
    slug: "sa-roqueta",
    name: "Sa Roqueta",
    description: "Marisco tradicional.",
    difficulty: "low",
    zone: "west",
    priceText: "50–80€",
    priceType: "paid",
    town: "Palma",
    googleMapsUrl: buildGoogleMapsUrl("Sa Roqueta Palma Mallorca"),
    tags: ["seafood", "traditional", "palma"],
  },
  {
    id: "restaurant-aromata",
    slug: "aromata",
    name: "Aromata",
    description: "Cocina moderna accesible.",
    difficulty: "low",
    zone: "west",
    priceText: "40–50€",
    priceType: "paid",
    town: "Palma",
    googleMapsUrl: buildGoogleMapsUrl("Aromata Palma Mallorca"),
    tags: ["modern", "palma"],
  },
  {
    id: "restaurant-clandesti",
    slug: "clandesti-taller-gastronomic",
    name: "Clandestí Taller Gastronòmic",
    description: "Experiencia creativa gastronómica.",
    difficulty: "low",
    zone: "west",
    priceText: "60–90€",
    priceType: "paid",
    town: "Palma",
    googleMapsUrl: buildGoogleMapsUrl("Clandestí Taller Gastronòmic Palma Mallorca"),
    tags: ["creative", "tasting", "palma"],
  },
  {
    id: "restaurant-es-raco-des-teix",
    slug: "es-raco-des-teix",
    name: "Es Racó d'Es Teix",
    description: "Restaurante de montaña gourmet.",
    difficulty: "high",
    zone: "west",
    priceText: "90–120€",
    priceType: "paid",
    town: "Deià",
    googleMapsUrl: buildGoogleMapsUrl("Es Racó d'Es Teix Deià Mallorca"),
    tags: ["gourmet", "mountain", "deia"],
  },
  {
    id: "restaurant-sa-pedrera-des-pujol",
    slug: "sa-pedrera-des-pujol",
    name: "Sa Pedrera d'Es Pujol",
    description: "Restaurante tranquilo con vistas.",
    difficulty: "medium",
    zone: "west",
    priceText: "50–70€",
    priceType: "paid",
    town: "Deià",
    googleMapsUrl: buildGoogleMapsUrl("Sa Pedrera d'Es Pujol Deià Mallorca"),
    tags: ["views", "quiet", "deia"],
  },
  {
    id: "restaurant-es-tast-de-na-silvia",
    slug: "es-tast-de-na-silvia",
    name: "Es Tast de na Silvia",
    description: "Cocina sostenible muy local.",
    difficulty: "medium",
    zone: "north",
    priceText: "50–80€",
    priceType: "paid",
    town: "Palma",
    googleMapsUrl: buildGoogleMapsUrl("Es Tast de na Silvia Palma Mallorca"),
    tags: ["sustainable", "local"],
  },
];
