import type { PlaceEntity } from "./types";
import { buildGoogleMapsUrl } from "./types";

export const sunsetSpotsSeed: PlaceEntity[] = [
  {
    id: "sunset-sa-foradada",
    slug: "sa-foradada",
    name: "Sa Foradada",
    description: "Sunset brutal con restaurante abajo.",
    difficulty: "high",
    zone: "west",
    priceText: "Gratis",
    priceType: "free",
    town: "Deià",
    googleMapsUrl: buildGoogleMapsUrl("Sa Foradada Deià Mallorca"),
    tags: ["sunset", "iconic", "viewpoint"],
  },
  {
    id: "sunset-cala-en-basset",
    slug: "cala-en-basset",
    name: "Cala en Basset",
    description: "Sunset salvaje sin turismo.",
    difficulty: "very-high",
    zone: "west",
    priceText: "Gratis",
    priceType: "free",
    town: "Sant Elm",
    googleMapsUrl: buildGoogleMapsUrl("Cala en Basset Sant Elm Mallorca"),
    tags: ["wild", "hike", "sunset"],
  },
  {
    id: "sunset-puig-de-santa-magdalena",
    slug: "puig-de-santa-magdalena",
    name: "Puig de Santa Magdalena",
    description: "Vista 360º de la isla.",
    difficulty: "medium",
    zone: "north",
    priceText: "Gratis",
    priceType: "free",
    town: "Inca",
    googleMapsUrl: buildGoogleMapsUrl("Puig de Santa Magdalena Inca Mallorca"),
    tags: ["panoramic", "hill", "sunset"],
  },
  {
    id: "sunset-cap-andritxol",
    slug: "cap-andritxol",
    name: "Cap Andritxol",
    description: "Acantilados poco conocidos.",
    difficulty: "medium",
    zone: "west",
    priceText: "Gratis",
    priceType: "free",
    town: "Andratx",
    googleMapsUrl: buildGoogleMapsUrl("Cap Andritxol Andratx Mallorca"),
    tags: ["cliffs", "hidden", "sunset"],
  },
  {
    id: "sunset-torre-del-verger",
    slug: "torre-del-verger",
    name: "Torre del Verger",
    description: "Mirador secreto en la carretera de Tramuntana.",
    difficulty: "low",
    zone: "west",
    priceText: "Gratis",
    priceType: "free",
    town: "Banyalbufar",
    googleMapsUrl: buildGoogleMapsUrl("Torre del Verger Banyalbufar Mallorca"),
    tags: ["viewpoint", "tramuntana", "sunset"],
  },
  {
    id: "sunset-cala-tuent",
    slug: "cala-tuent-sunset",
    name: "Cala Tuent",
    description: "Sunset con montaña y mar.",
    difficulty: "medium",
    zone: "north-west",
    priceText: "Gratis",
    priceType: "free",
    town: "Escorca",
    googleMapsUrl: buildGoogleMapsUrl("Cala Tuent Escorca Mallorca"),
    tags: ["mountains", "sea", "sunset"],
  },
  {
    id: "sunset-puig-de-randa",
    slug: "puig-de-randa",
    name: "Puig de Randa",
    description: "Vista aérea espectacular.",
    difficulty: "medium",
    zone: "center",
    priceText: "Gratis",
    priceType: "free",
    town: "Llucmajor",
    googleMapsUrl: buildGoogleMapsUrl("Puig de Randa Llucmajor Mallorca"),
    tags: ["panoramic", "hill", "sunset"],
  },
  {
    id: "sunset-faro-cap-blanc",
    slug: "faro-cap-blanc",
    name: "Faro de Cap Blanc",
    description: "Acantilado salvaje poco masificado.",
    difficulty: "low",
    zone: "south",
    priceText: "Gratis",
    priceType: "free",
    town: "Llucmajor",
    googleMapsUrl: buildGoogleMapsUrl("Faro de Cap Blanc Mallorca"),
    tags: ["lighthouse", "cliffs", "sunset"],
  },
  {
    id: "sunset-son-marroig-exterior",
    slug: "son-marroig-exterior",
    name: "Son Marroig (zona exterior)",
    description: "Alternativa sin entrar al museo.",
    difficulty: "low",
    zone: "west",
    priceText: "Gratis",
    priceType: "free",
    town: "Deià",
    googleMapsUrl: buildGoogleMapsUrl("Son Marroig Deià Mallorca"),
    tags: ["viewpoint", "classic", "sunset"],
  },
  {
    id: "sunset-cala-banyalbufar",
    slug: "cala-banyalbufar-sunset",
    name: "Cala Banyalbufar",
    description: "Sunset entre terrazas.",
    difficulty: "medium",
    zone: "west",
    priceText: "Gratis",
    priceType: "free",
    town: "Banyalbufar",
    googleMapsUrl: buildGoogleMapsUrl("Cala Banyalbufar Mallorca"),
    tags: ["terraces", "coast", "sunset"],
  },
  {
    id: "sunset-es-pontas",
    slug: "es-pontas",
    name: "Es Pontàs",
    description: "Arco natural frente al mar.",
    difficulty: "medium",
    zone: "south",
    priceText: "Gratis",
    priceType: "free",
    town: "Santanyí",
    googleMapsUrl: buildGoogleMapsUrl("Es Pontàs Santanyí Mallorca"),
    tags: ["natural-arch", "sea", "sunset"],
  },
  {
    id: "sunset-cala-murta",
    slug: "cala-murta-sunset",
    name: "Cala Murta",
    description: "Sunset íntimo.",
    difficulty: "medium",
    zone: "north",
    priceText: "Gratis",
    priceType: "free",
    town: "Formentor",
    googleMapsUrl: buildGoogleMapsUrl("Cala Murta Formentor Mallorca"),
    tags: ["quiet", "formentor", "sunset"],
  },
  {
    id: "sunset-portopetro",
    slug: "portopetro-sunset",
    name: "Portopetro",
    description: "Puerto pequeño con sunset chill.",
    difficulty: "low",
    zone: "east",
    priceText: "Gratis",
    priceType: "free",
    town: "Santanyí",
    googleMapsUrl: buildGoogleMapsUrl("Portopetro Mallorca"),
    tags: ["port", "chill", "sunset"],
  },
  {
    id: "sunset-es-trenc-final",
    slug: "es-trenc-final",
    name: "Es Trenc (zona final)",
    description: "Menos gente al final de playa.",
    difficulty: "low",
    zone: "south",
    priceText: "Gratis",
    priceType: "free",
    town: "Campos",
    googleMapsUrl: buildGoogleMapsUrl("Es Trenc Campos Mallorca"),
    tags: ["beach", "wide", "sunset"],
  },
  {
    id: "sunset-s-estaca",
    slug: "s-estaca",
    name: "S'Estaca",
    description: "Zona exclusiva pero visible desde fuera.",
    difficulty: "high",
    zone: "west",
    priceText: "Gratis",
    priceType: "free",
    town: "Deià",
    googleMapsUrl: buildGoogleMapsUrl("S'Estaca Deià Mallorca"),
    tags: ["exclusive", "coast", "sunset"],
  },
  {
    id: "sunset-cala-deia",
    slug: "cala-deia-sunset",
    name: "Cala Deià (tarde)",
    description: "Luz cálida sobre roca.",
    difficulty: "medium",
    zone: "west",
    priceText: "Gratis",
    priceType: "free",
    town: "Deià",
    googleMapsUrl: buildGoogleMapsUrl("Cala Deià Mallorca"),
    tags: ["rocky", "golden-hour", "sunset"],
  },
  {
    id: "sunset-mirador-es-colomer",
    slug: "mirador-es-colomer",
    name: "Mirador Es Colomer (tarde)",
    description: "Menos saturado que amanecer.",
    difficulty: "low",
    zone: "north",
    priceText: "Gratis",
    priceType: "free",
    town: "Formentor",
    googleMapsUrl: buildGoogleMapsUrl("Mirador Es Colomer Mallorca"),
    tags: ["viewpoint", "north", "sunset"],
  },
  {
    id: "sunset-cala-figuera-puerto",
    slug: "cala-figuera-puerto",
    name: "Cala Figuera puerto",
    description: "Sunset en puerto pescador.",
    difficulty: "low",
    zone: "south",
    priceText: "Gratis",
    priceType: "free",
    town: "Santanyí",
    googleMapsUrl: buildGoogleMapsUrl("Cala Figuera Santanyí Mallorca"),
    tags: ["fishing-port", "quiet", "sunset"],
  },
  {
    id: "sunset-estellencs",
    slug: "estellencs-sunset",
    name: "Estellencs",
    description: "Pueblo, mar y montaña.",
    difficulty: "low",
    zone: "west",
    priceText: "Gratis",
    priceType: "free",
    town: "Estellencs",
    googleMapsUrl: buildGoogleMapsUrl("Estellencs Mallorca"),
    tags: ["village", "coast", "mountains"],
  },
  {
    id: "sunset-son-serra",
    slug: "son-serra-wild-side",
    name: "Playa de Son Serra (lado salvaje)",
    description: "Zona virgen para sunset.",
    difficulty: "low",
    zone: "north",
    priceText: "Gratis",
    priceType: "free",
    town: "Artà",
    googleMapsUrl: buildGoogleMapsUrl("Son Serra de Marina Artà Mallorca"),
    tags: ["wild", "beach", "sunset"],
  },
];
